
---
- name: Configure production server
  hosts: prod
  become: yes

  tasks:

  - name: Ping production server
    ping:

  - name: Install Apache WebServer at production
    apt: name=apache2 state=latest

  - name: Start Apache WebServer
    service: name=apache2 state=started enabled=yes
