---
 - name: Clone github repo
   hosts: dev
   become: yes

   tasks:

   - name: Ping development server
     ping:

   - name: Clone a github repository
     git:
       repo: https://github.com/terra144481/final_project_epam.git
       dest: /home/ubuntu/git/
       clone: yes
       update: yes